name: project

services:
  frontend:
    image: "${FRONTEND_IMAGE}:${GITHUB_SHA}"
    environment:
      - API_URL=${API_URL}    
    ports:
     - "3000:3000"
    networks:
        - app-network
    depends_on:
       backend:
        condition: service_healthy
       worker:
        condition: service_healthy
    mem_limit: 200m
    cpus: 0.5

  backend:
    image: "${BACKEND_IMAGE}:${GITHUB_SHA}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    mem_limit: 200m
    cpus: 0.5

  worker:
    image: "${WORKER_IMAGE}:${GITHUB_SHA}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - app-network    
    depends_on:
      redis:
        condition: service_healthy
    mem_limit: 200m
    cpus: 0.5
  
  redis:
    image: "${REDIS_IMAGE}"
    networks: 
      - app-network
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}" 
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping || exit 1
      start_period: 5s
      start_interval: 1s
      interval: 10s
      timeout: 3s
      retries: 3
    mem_limit: 200m
    cpus: 0.5

networks:
  app-network:
    

