name: CI/CD Pipeline

# TODO: Optimization of entire workflow 
on:
  push:
    branches:
      - main
  
env:
  HOST: ${{vars.HOST}}
  REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
  PORT: ${{secrets.PORT}}
  APP_ENV: ${{vars.APP_ENV}}
  API_URL: ${{secrets.API_URL}}

jobs:

  lint:
    runs-on: ubuntu-latest
    #TODO: remove after troubleshooting
    if: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
    #setting up python
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install linting tools
        run: |
          echo "Installing linting tools. . ."
          npm install -g eslint

      - name: Install Python linting tools
        run: |                    
          pip install flake8         
          

      - name: lint frontend code
        working-directory: ./services/frontend
        run: |
          echo "Linting frontend code. . ."                  
          npm ci          
          npm run lint
        
      - name: lint api code    
        run: |
          echo "Linting api code. . ."
          flake8 --exit-zero ./services/api


      - name: lint worker code
        run: |        
          echo "Linting worker code. . ."
          flake8 --exit-zero ./services/worker
      
      - name: Lint frontend Dockerfile       
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/frontend/Dockerfile"
          failure-threshold: "error"
      
      - name: Lint api Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/api/Dockerfile"
          failure-threshold: "error"
          
      - name: Lint worker Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/worker/Dockerfile"
          failure-threshold: "error"
  
  test:
  # TODO: remove after troubleshooting
    if: false
  #  needs: lint
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install Application dependencies
        working-directory: ./services/api
        run: |
          pip install -r requirements.txt
    
      - name: Install Python testing tools
        run: | 
          pip install pytest pytest-cov

      - name: Run tests
        working-directory: ./services/api        
        run: |
          pytest --cov=main test.py --cov-report xml:coverage.xml
          ls -l 

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: pytest-coverage-report
          path: ./services/api/coverage.xml
          retention-days: 2
  
  build:
  # TODO: remove after troubleshooting
  #  needs: test
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:3
        ports:
          - "5000:5000"
    
    env:
      REGISTRY_URL: ${{secrets.REGISTRY_URL}}
      
      # SHA tagged images (ST)
      ST_FRONTEND_IMAGE: ${{secrets.REGISTRY_URL}}/frontend:${{ github.sha }}
      ST_API_IMAGE: ${{secrets.REGISTRY_URL}}/api:${{ github.sha }}
      ST_WORKER_IMAGE: ${{secrets.REGISTRY_URL}}/worker:${{ github.sha }}

      # Latest tagged images (LT)
      LT_FRONTEND_IMAGE: ${{secrets.REGISTRY_URL}}/frontend:latest
      LT_API_IMAGE: ${{secrets.REGISTRY_URL}}/api:latest
      LT_WORKER_IMAGE: ${{secrets.REGISTRY_URL}}/worker:latest

    steps:     
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Build frontend Docker image
        working-directory: ./services/frontend
        run: |
          echo "Building frontend Docker image. . ."
          docker build -t ${ST_FRONTEND_IMAGE} -t "${LT_FRONTEND_IMAGE}" .

      - name: Build api Docker image
        working-directory: ./services/api
        run: |
          echo "Building api Docker image. . ."
          docker build -t ${ST_API_IMAGE} -t "${LT_API_IMAGE}" .

      - name: Build worker Docker image
        working-directory: ./services/worker
        run: |
          echo "Building worker Docker image. . ."
          docker build -t ${ST_WORKER_IMAGE} -t "${LT_WORKER_IMAGE}" .

      - name: Push Docker images to local registry
        run: |
          docker push --all-tags ${REGISTRY_URL}/frontend
          docker push --all-tags ${REGISTRY_URL}/api
          docker push --all-tags ${REGISTRY_URL}/worker
        
      - name: Save images as tar file
        run: |
          docker save \
          $ST_FRONTEND_IMAGE \
          $LT_FRONTEND_IMAGE \
          $ST_API_IMAGE \
          $LT_API_IMAGE \
          $ST_WORKER_IMAGE \
          $LT_WORKER_IMAGE \
          -o images.tar
          
      - name: upload images as artifact
        uses: actions/upload-artifact@v7
        with:
          name: images
          path: images.tar
           

# TODO
# Does using matrix strategy optimize pipeline execution time?
# Replace all this job with a matrix strategy to optimize pipeline execution time  
  security-scan:
    # TODO: remove after troubleshooting
    if: false 
    #needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: download images artifact
        uses: actions/download-artifact@v7
        with:
          name: images
      
      - name: Load Docker images from tar files
        run: |
          docker load -i images.tar

    # Non-blocking trivy with visibility

      - name: frontend trivy non-blocking scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/frontend:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: api trivy non-blocking scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/api:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
        
      - name: worker trivy non-blocking scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/worker:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL'

# Blocking scan
      - name: frontend trivy scan
        id: frontend-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/frontend:${{ github.sha }}
          format: 'sarif'
          output: 'frontend-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true
          
      - name: api trivy scan
        id: api-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/api:${{ github.sha }}
          format: 'sarif'
          output: 'api-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true
                
      - name: worker trivy scan
        id: worker-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/worker:${{ github.sha }}
          format: 'sarif'
          output: 'worker-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true


      # Upload trivy scan as artifact
      - name: Upload trivy scan as artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: trivy-scan
          path: |
            frontend-scan.sarif
            api-scan.sarif
            worker-scan.sarif
      
      
      # Upload trivy in GitHub security tab
      - name: Upload frontend trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: frontend-scan.sarif
          category: frontend-trivy-scan
      
      - name: Upload api trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: api-scan.sarif
          category: api-trivy-scan
      
      - name: Upload worker trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: worker-scan.sarif
          category: worker-trivy-scan
            

      # Fail pipeline if any trivy scan fails
      - name: Fail pipeline if any trivy scan fails
        if: always()
        run: |
        
          if [[ "${{ steps.frontend-trivy-scan.outcome }}" == "failure" || "${{ steps.api-trivy-scan.outcome }}" == "failure" || "${{ steps.worker-trivy-scan.outcome }}" == "failure" ]]; then
            echo "One or more trivy scans failed. Failing the pipeline."
            exit 1
          fi
    
  integration-test:
    # TODO: remove after troubleshooting
    if: false
    #needs: security-scan
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download frontend artifact
        uses: actions/download-artifact@v7
        with:
          name: images

      
      - name: Load Docker images from tar files
        run: |
          docker load -i images.tar

      - name: Run integration tests using docker compose
        run: |
          docker compose up -d
     
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"
      
      - name: install requests module
        run: |
          pip install requests

      - name: submit job through frontend
        run: |
          python ./tests/submit_job.py

      - name: tear down stack
        if: always()
        run: |
          docker compose down
      
  deploy:
    # TODO: remove after troubleshooting
    #needs: integration-test
    needs: build
    runs-on: ubuntu-latest 
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' 

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: download image artifacts
        uses: actions/download-artifact@v7
        with:
          name: images        

      - name: Create environment variables file
        run: |
          echo "Creating environment variables file. . ."
          cat > .env <<EOL
          REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}
          HOST=${{vars.HOST}}
          PORT=${{secrets.PORT}}
          API_URL=${{secrets.API_URL}}
          GITHUB_SHA=${{github.sha}}
          REGISTRY_URL=${{secrets.REGISTRY_URL}}
          APPDIR_PATH=${{secrets.APPDIR_PATH}}
          EOL
      
    # TODO: remove debugging step
      - name: view all files
        run: |
          ls -la
          

      - name: Upload environment variables file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: ".env"
          target: ${{secrets.APPDIR_PATH}}

      - name: Copy images to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "images.tar"
          target: ${{secrets.APPDIR_PATH}}
      
      - name: copy up-to-date compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "docker-compose.yaml"
          target: ${{secrets.APPDIR_PATH}}
    
      - name: Connect to server and deploy
        id: ssh
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}

          # TODO: Implement rolling update with docker swarm. Debug script 
          script: |
            cd $APPDIR_PATH            
            pwd 
            ls -la
            docker load -i images.tar
            docker compose down
            docker compose up -d

#TODO: Remove debugging step
      - name: capture stdout
        if: always() 
        run: |
          echo "SSH Output: ${{ steps.ssh.outputs.stdout }}" 

