name: CI/CD Pipeline

on: 
  workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
    #setting up python
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install linting tools
        run: |
          echo "Installing linting tools. . ."
          npm install -g eslint

      - name: Install Python linting tools
        run: |                    
          pip install flake8         
          

      - name: lint frontend code
        working-directory: ./services/frontend
        run: |
          echo "Linting frontend code. . ."                  
          npm ci          
          npm run lint
        
      - name: lint api code    
        run: |
          echo "Linting api code. . ."
          flake8 --exit-zero ./services/api


      - name: lint worker code
        run: |        
          echo "Linting worker code. . ."
          flake8 --exit-zero ./services/worker
      
      - name: Lint frontend Dockerfile       
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/frontend/Dockerfile"
          failure-threshold: "error"
      
      - name: Lint api Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/api/Dockerfile"
          failure-threshold: "error"
          
      - name: Lint worker Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/worker/Dockerfile"
          failure-threshold: "error"
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install Application dependencies
        working-directory: ./services/api
        run: |
          pip install -r requirements.txt
    
      - name: Install Python testing tools
        run: | 
          pip install pytest pytest-cov

      - name: Run tests
        working-directory: ./services/api        
        run: |
          pytest --cov=main test.py --cov-report xml:coverage.xml
          ls -l 

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: pytest-coverage-report
          path: ./services/api/coverage.xml
          retention-days: 2
  
  build:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:3
        ports:
          - "5000:5000"

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Build frontend Docker image
        working-directory: ./services/frontend
        run: |
          echo "Building frontend Docker image. . ."
          docker build -t localhost:5000/frontend:latest -t "localhost:5000/frontend:${GITHUB_SHA}" . 

      - name: Build api Docker image
        working-directory: ./services/api
        run: |
          echo "Building api Docker image. . ."
          docker build -t localhost:5000/api:latest -t "localhost:5000/api:${GITHUB_SHA}" .

      - name: Build worker Docker image
        working-directory: ./services/worker
        run: |
          echo "Building worker Docker image. . ."
          docker build -t localhost:5000/worker:latest -t "localhost:5000/worker:${GITHUB_SHA}" .

      - name: Push Docker images to local registry
        run: |
          docker push localhost:5000/frontend:latest
          docker push localhost:5000/api:latest
          docker push localhost:5000/worker:latest
        
      # TODO: Upload a single image as an artifact 
      - name: Save images as tar files
        run: |
          docker save localhost:5000/frontend:latest -o frontend.tar
          docker save localhost:5000/api:latest -o api.tar
          docker save localhost:5000/worker:latest -o worker.tar
          
      - name: upload frontend image as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: frontend-image
          path: frontend.tar
      
      - name: upload api docker image as artifact
        uses: actions/upload-artifact@v7
        with:
          name: api-image
          path: api.tar

      - name: upload worker docker image as artifact
        uses: actions/upload-artifact@v7
        with:
          name: worker-image
          path: worker.tar

# TODO
# Does using matrix strategy optimize pipeline execution time?
# Replace all this job with a matrix strategy to optimize pipeline execution time  
  sec-scan:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

# TODO: Use docker load images to download images from tar
    steps:
      - name: download frontend artifact
        uses: actions/download-artifact@v7
        with:
          name: frontend-image

      - name: download api image artifact
        uses: actions/download-artifact@v7
        with:
          name: api-image

      - name: download worker image artifact
        uses: actions/download-artifact@v7
        with:
          name: worker-image

    # Non-blocking trivy with visibility

      - name: frontend trivy non-blocking scan
        uses: aquasecurity/trivy-action@master
        with:
          input: 'frontend.tar'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: api trivy non-blocking scan
        uses: aquasecurity/trivy-action@master
        with:
          input: 'api.tar'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
        
      - name: worker trivy non-blocking scan
        uses: aquasecurity/trivy-action@master
        with:
          input: 'worker.tar'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL'

# Blocking scan
      - name: frontend trivy scan
        id: frontend-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          input: 'frontend.tar'
          format: 'sarif'
          output: 'frontend-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true
          
      - name: api trivy scan
        id: api-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          input: 'api.tar'
          format: 'sarif'
          output: 'api-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true
                
      - name: worker trivy scan
        id: worker-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          input: 'worker.tar'
          format: 'sarif'
          output: 'worker-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true


      # Upload trivy scan as artifact
      - name: Upload trivy scan as artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: trivy-scan
          path: |
            frontend-scan.sarif
            api-scan.sarif
            worker-scan.sarif
      
      # Organize trivy scan sarifs into a folder
      - name: Organize trivy scan sarifs into a folder
        run: |
          mkdir -p sarif-results
          mv *.sarif sarif-results/
      
      # Upload trivy in GitHub security tab
      - name: Upload frontend trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: frontend-scan.sarif
          category: frontend-trivy-scan
      
      - name: Upload api trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: api-scan.sarif
          category: api-trivy-scan
      
      - name: Upload worker trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: worker-scan.sarif
          category: worker-trivy-scan
            

      # Fail pipeline if any trivy scan fails
      - name: Fail pipeline if any trivy scan fails
        if: always()
        run: |
        
          if [[ "${{ steps.frontend-trivy-scan.outcome }}" == "failure" || "${{ steps.api-trivy-scan.outcome }}" == "failure" || "${{ steps.worker-trivy-scan.outcome }}" == "failure" ]]; then
            echo "One or more trivy scans failed. Failing the pipeline."
            exit 1
          fi
    
