name: CI/CD Pipeline

on: 
  
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

  workflow_dispatch:

jobs:

  lint:
# TODO: Remove after tshoot
    if: false  
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: set up python to install linting tools
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install eslint
        run: |
          npm install -g eslint

      - name: Install flake8
        run: |                    
          pip install flake8         

      - name: lint frontend code
        working-directory: ./services/frontend
        run: |                 
          npm ci          
          npm run lint

      - name: lint api code    
        run: |
          flake8  ./services/api

      - name: lint worker code
        run: |        
          flake8  ./services/worker
      
      - name: Lint frontend Dockerfile       
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/frontend/Dockerfile"
          failure-threshold: "error"
      
      - name: Lint api Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/api/Dockerfile"
          failure-threshold: "error"
          
      - name: Lint worker Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./services/worker/Dockerfile"
          failure-threshold: "error"
  
  test:
# TODO: Remove after tshoot
    if: false 
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install Application dependencies
        working-directory: ./services/api
        run: |
          pip install -r requirements.txt
    
      - name: Install Python testing tools
        run: | 
          pip install pytest pytest-cov

      - name: Run tests
        working-directory: ./services/api        
        run: |
          pytest --cov=main test.py --cov-report xml:coverage.xml
          ls -l 

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: pytest-coverage-report
          path: ./services/api/coverage.xml
          retention-days: 2
  
  build:    
    runs-on: ubuntu-latest
# TODO: Remove after tshoot
#    needs: test

    services:
      registry:
        image: registry:3
        ports:
          - "5000:5000"
    
    env:
      REGISTRY_URL: ${{vars.REGISTRY_URL}}

      # SHA tagged images (ST)
      ST_FRONTEND_IMAGE: ${{vars.REGISTRY_URL}}/frontend:${{ github.sha }}
      ST_API_IMAGE: ${{vars.REGISTRY_URL}}/api:${{ github.sha }}
      ST_WORKER_IMAGE: ${{vars.REGISTRY_URL}}/worker:${{ github.sha }}

      # Latest tagged images (LT)
      LT_FRONTEND_IMAGE: ${{vars.REGISTRY_URL}}/frontend:latest
      LT_API_IMAGE: ${{vars.REGISTRY_URL}}/api:latest
      LT_WORKER_IMAGE: ${{vars.REGISTRY_URL}}/worker:latest

    steps:     
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Build frontend Docker image
        working-directory: ./services/frontend
        run: |
          docker build -t ${ST_FRONTEND_IMAGE} -t "${LT_FRONTEND_IMAGE}" .

      - name: Build api Docker image
        working-directory: ./services/api
        run: |
          docker build -t ${ST_API_IMAGE} -t "${LT_API_IMAGE}" .

      - name: Build worker Docker image
        working-directory: ./services/worker
        run: |
          docker build -t ${ST_WORKER_IMAGE} -t "${LT_WORKER_IMAGE}" .

      - name: Push Docker images to local registry
        run: |
          docker push --all-tags ${REGISTRY_URL}/frontend
          docker push --all-tags ${REGISTRY_URL}/api
          docker push --all-tags ${REGISTRY_URL}/worker
        
      - name: Save images as tar file
        run: |
          docker save \
          $ST_FRONTEND_IMAGE \
          $LT_FRONTEND_IMAGE \
          $ST_API_IMAGE \
          $LT_API_IMAGE \
          $ST_WORKER_IMAGE \
          $LT_WORKER_IMAGE \
          -o images.tar
          
      - name: upload images as artifact
        uses: actions/upload-artifact@v7
        with:
          name: images
          path: images.tar
             
  security-scan:
  # TODO: Remove after tshoot
    if: false 
    runs-on: ubuntu-latest
    needs: build

    #Permission required for trivy scan results upload to GitHub security tab
    permissions:
      contents: read
      security-events: write

    steps:
      - name: download images artifact
        uses: actions/download-artifact@v7
        with:
          name: images
      
      - name: Load Docker images from tar files
        run: |
          docker load -i images.tar

      - name: frontend trivy scan
        id: frontend-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{vars.REGISTRY_URL}}/frontend:${{ github.sha }}
          format: 'sarif'
          output: 'frontend-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true
          
      - name: api trivy scan
        id: api-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{vars.REGISTRY_URL}}/api:${{ github.sha }}
          format: 'sarif'
          output: 'api-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true
                
      - name: worker trivy scan
        id: worker-trivy-scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{vars.REGISTRY_URL}}/worker:${{ github.sha }}
          format: 'sarif'
          output: 'worker-scan.sarif'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          limit-severities-for-sarif: true

      # Upload trivy scan as artifact
      - name: Upload trivy scan as artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: trivy-scan
          path: |
            frontend-scan.sarif
            api-scan.sarif
            worker-scan.sarif
           
      # Upload trivy in GitHub security tab
      - name: Upload frontend trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: frontend-scan.sarif
          category: frontend-trivy-scan
      
      - name: Upload api trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: api-scan.sarif
          category: api-trivy-scan
      
      - name: Upload worker trivy scan to GitHub security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: worker-scan.sarif
          category: worker-trivy-scan
            
      - name: Log the service that fails trivy scan
        if: always()
        run: |
          if [[ "${{ steps.frontend-trivy-scan.outcome }}" == "failure" ]]; then
            echo "Critical vulnerabilities found in frontend image. Please check the scan report for details."
          fi

          if [[ "${{ steps.api-trivy-scan.outcome }}" == "failure" ]]; then
            echo "Critical vulnerabilities found in API image. Please check the scan report for details."
          fi

          if [[ "${{ steps.worker-trivy-scan.outcome }}" == "failure" ]]; then
            echo "Critical vulnerabilities found in worker image. Please check the scan report for details."
          fi
      
      - name: Fail pipeline if any trivy scan fails
        if: always()
        run: |
          if [[ "${{ steps.frontend-trivy-scan.outcome }}" == "failure" ]] ||
             [[ "${{ steps.api-trivy-scan.outcome }}" == "failure" ]] || 
             [[ "${{ steps.worker-trivy-scan.outcome }}" == "failure" ]]; then            
            echo "One or more security scans failed. Failing the pipeline."
            exit 1
          fi
    
  integration-test:
# TODO: Remove after tshoot
    runs-on: ubuntu-latest
    needs: build
#    needs: security-scan 
    env:
      REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      API_URL: ${{secrets.API_URL}}
      FRONTEND_IMAGE: ${{vars.REGISTRY_URL}}/frontend:${{ github.sha }}
      BACKEND_IMAGE: ${{vars.REGISTRY_URL}}/api:${{ github.sha }}
      WORKER_IMAGE: ${{vars.REGISTRY_URL}}/worker:${{ github.sha }}
      REDIS_IMAGE: ${{vars.REDIS_IMAGE}}

    steps: 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download images artifact
        uses: actions/download-artifact@v7
        with:
          name: images
      
      - name: Load Docker images from tar files
        run: |
          docker load -i images.tar

      - name: Run integration tests using docker compose
        id: run-integration-tests                   
        run: |
          docker compose up -d
     
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: "pip"
      
      - name: install requests module for testing job submission through frontend
        run: |
          pip install requests

      - name: Test job submission through frontend
        run: |
          python ./tests/submit_job.py
      
      - name: Collect logs on integration test failure  
        if: failure() && steps.run-integration-tests.outcome == 'failure'      
        run: |
          ./debug/integration_test_logs.sh
      
      - name: Upload integration test logs
        if: failure() && steps.run-integration-tests.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: integration_test_logs
          path: integration_test_logs

      - name: tear down stack
        if: always()
        run: |
          docker compose down
      
  deploy:
    runs-on: ubuntu-latest 
    needs: integration-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' 

    steps:
      - name: checkout code
        uses: actions/checkout@v2        

      - name: Create required application environment variables
        run: |
          cat > .env <<EOL
          REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}
          REDIS_HOST=${{secrets.REDIS_HOST}}
          REDIS_PORT=${{secrets.REDIS_PORT}}
          API_URL=${{secrets.API_URL}}
          GITHUB_SHA=${{github.sha}}
          REGISTRY_URL=${{vars.REGISTRY_URL}}
          APPDIR_PATH=${{secrets.APPDIR_PATH}}
          FRONTEND_IMAGE: ${{vars.REGISTRY_URL}}/frontend:${{ github.sha }}
          BACKEND_IMAGE: ${{vars.REGISTRY_URL}}/api:${{ github.sha }}
          WORKER_IMAGE: ${{vars.REGISTRY_URL}}/worker:${{ github.sha }}
          REDIS_IMAGE: ${{vars.REDIS_IMAGE}}
          EOL

      - name: Upload environment variables file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: ".env"
          target: ${{secrets.APPDIR_PATH}}

      - name: download image artifacts
        uses: actions/download-artifact@v7
        with:
          name: images

      - name: Copy images to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "images.tar"
          target: ${{secrets.APPDIR_PATH}}
      
      - name: copy up-to-date compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "docker-compose.yaml"
          target: ${{secrets.APPDIR_PATH}}
    
      - name: Connect to server and deploy
        env:
          APPDIR_PATH: ${{secrets.APPDIR_PATH}}
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          envs: APPDIR_PATH          
          script: |
            cd $APPDIR_PATH            
            pwd 
            ls -la
            docker load -i images.tar
            docker compose down
            docker compose up -d


