name: Hello world

on: 
  workflow_dispatch

jobs:

  docker_linter:
    runs-on: ubuntu-latest

    steps:

        - name: Check out code
          uses: actions/checkout@v2


        - name: Install Python linting tools
          working-directory: ./services
          run: |
            python3 -m venv venv
            source venv/bin/activate
            pip install flake8
            echo "$PATH"
            which flake8

        - name: lint backend code
          run: |
            PATH=./services/venv/bin:$PATH
            echo "$PATH"
            which flake8
            echo "Linting backend code. . ."
            flake8 ./services/api